### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by ntmedia77654** [drobnikj/crawler-google-places#1]
Hello drobnikj,

I just tried a run on Apify with "place_id:..." as input and had to abort it after 5 loops getting the following error over and over again.

Error: Evaluation failed: TypeError: Cannot read property 'trim' of undefined
2019-04-28T17:40:34.201Z     at __puppeteer_evaluation_script__:6:88
2019-04-28T17:40:34.203Z     at ExecutionContext.evaluateHandle (/home/myuser/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
2019-04-28T17:40:34.205Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-04-28T17:40:34.206Z   -- ASYNC --
2019-04-28T17:40:34.208Z     at ExecutionContext.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:108:27)
2019-04-28T17:40:34.210Z     at ExecutionContext.evaluate (/home/myuser/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
2019-04-28T17:40:34.212Z     at ExecutionContext.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:109:23)
2019-04-28T17:40:34.214Z     at DOMWorld.evaluate (/home/myuser/node_modules/puppeteer/lib/DOMWorld.js:105:20)
2019-04-28T17:40:34.215Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-04-28T17:40:34.217Z   -- ASYNC --
2019-04-28T17:40:34.219Z     at Frame.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:108:27)
2019-04-28T17:40:34.221Z     at Page.evaluate (/home/myuser/node_modules/puppeteer/lib/Page.js:809:43)
2019-04-28T17:40:34.223Z     at Page.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:109:23)
2019-04-28T17:40:34.224Z     at extractPlaceDetail (/home/myuser/src/places_crawler.js:104:43)
2019-04-28T17:40:34.226Z     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by drobnikj** [comment]
Hi @ntmedia77654 ,

I just tested it and it works with input.
```json
{
  "searchString": "place_id:ChIJp4JiUCNP0xQR1JaSjpW_Hms",
  "proxyConfig": {
    "useApifyProxy": true
  },
  "includeReviews": false,
  "includeImages": false,
  "lat": "48.97797",
  "lng": "14.44565",
  "zoom": 10,
  "maxCrawledPlaces": 5
}
```

Can you share with me your input? I will test it.

**Comment by ntmedia77654** [comment]
Hi @drobnikj,

ok, thank you! I tried another place id and it worked for me too!

But the following input still does not work:

`{
  "searchString": "place_id:ChIJN6gdChTTlkcR0oV7M8qR8ZA",
  "proxyConfig": {
    "useApifyProxy": true
  },
  "includeReviews": true,
  "includeImages": false,
  "zoom": 10,
  "maxCrawledPlaces": 5
}`

Log:

`2019-04-30T14:10:21.124Z ACTOR: Creating Docker container
2019-04-30T14:10:21.184Z ACTOR: Starting Docker container
2019-04-30T14:10:22.290Z Starting X virtual framebuffer using: Xvfb :99 -ac -screen 0 1280x720x16 -nolisten tcp
2019-04-30T14:10:22.293Z Executing main command
2019-04-30T14:10:22.294Z _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
2019-04-30T14:10:22.296Z INFO: System info {"apifyVersion":"0.13.7","apifyClientVersion":"0.5.14","osType":"Linux","nodeVersion":"v10.15.3"}
2019-04-30T14:10:22.428Z INFO: Scraping Google Places for search string: "place_id:ChIJN6gdChTTlkcR0oV7M8qR8ZA"
2019-04-30T14:10:22.432Z INFO: Start url is "https://www.google.com/maps/search/"
2019-04-30T14:10:22.433Z INFO: Place ID found in search query. We will extract data from place_id:ChIJN6gdChTTlkcR0oV7M8qR8ZA.
2019-04-30T14:10:22.464Z WARNING: PuppeteerCrawler: options.maxOpenPagesPerInstance is deprecated. Use options.puppeteerPoolOptions instead.
2019-04-30T14:10:22.465Z WARNING: PuppeteerCrawler: options.retireInstanceAfterRequestCount is deprecated. Use options.puppeteerPoolOptions instead.
2019-04-30T14:10:22.486Z INFO: AutoscaledPool state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"maxOverloadedRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"maxOverloadedRatio":0.4,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"maxOverloadedRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"maxOverloadedRatio":0.3,"actualRatio":null}}}
2019-04-30T14:10:22.639Z INFO: Launching Puppeteer {"args":["--no-sandbox","--enable-resource-load-scheduler=false","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"],"headless":false,"defaultViewport":{"width":1366,"height":768},"proxyUrl":"http://auto:<redacted>@172.31.22.77:8011/"}
2019-04-30T14:10:26.973Z INFO: Open https://www.google.com/maps/place/?q=place_id:ChIJN6gdChTTlkcR0oV7M8qR8ZA with label: placeDetail
2019-04-30T14:10:29.454Z INFO: Extracting details from place url https://www.google.com/maps/place/?q=place_id:ChIJN6gdChTTlkcR0oV7M8qR8ZA
2019-04-30T14:10:35.633Z INFO: Infinite scroll for reviews list started, url: https://www.google.com/maps/place/Haus+Zauberfl%C3%B6te+-+Hotel+%26+Restaurant/@48.4697777,7.9449433,17z/data=!3m1!4b1!4m7!3m6!1s0x4796d3140a1da837:0x90f191ca337b85d2!8m2!3d48.4697777!4d7.947132!9m1!1b1
2019-04-30T14:11:22.488Z INFO: AutoscaledPool state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"maxOverloadedRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"maxOverloadedRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"maxOverloadedRatio":0.4,"actualRatio":0},"clientInfo":{"isOverloaded":false,"maxOverloadedRatio":0.3,"actualRatio":0}}}
2019-04-30T14:11:54.597Z INFO: AutoscaledPool state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"maxOverloadedRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"maxOverloadedRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"maxOverloadedRatio":0.4,"actualRatio":0},"clientInfo":{"isOverloaded":false,"maxOverloadedRatio":0.3,"actualRatio":0}}}

2019-04-30T14:12:22.491Z INFO: AutoscaledPool state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"maxOverloadedRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"maxOverloadedRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"maxOverloadedRatio":0.4,"actualRatio":0},"clientInfo":{"isOverloaded":false,"maxOverloadedRatio":0.3,"actualRatio":0}}}
2019-04-30T14:13:06.088Z INFO: Infinite scroll for reviews list finished, url: https://www.google.com/maps/place/Haus+Zauberfl%C3%B6te+-+Hotel+%26+Restaurant/@48.4697777,7.9449433,17z/data=!4m7!3m6!1s0x4796d3140a1da837:0x90f191ca337b85d2!8m2!3d48.4697777!4d7.947132!9m1!1b1
2019-04-30T14:13:06.151Z ERROR: BasicCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/place/?q=place_id:ChIJN6gdChTTlkcR0oV7M8qR8ZA","retryCount":1,"id":"DEP9zKM67nvu8Gi"}
2019-04-30T14:13:06.153Z   Error: Evaluation failed: TypeError: Cannot read property 'trim' of undefined
2019-04-30T14:13:06.155Z     at __puppeteer_evaluation_script__:6:88
2019-04-30T14:13:06.157Z     at ExecutionContext.evaluateHandle (/home/myuser/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
2019-04-30T14:13:06.158Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-04-30T14:13:06.163Z   -- ASYNC --
2019-04-30T14:13:06.165Z     at ExecutionContext.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:108:27)
2019-04-30T14:13:06.167Z     at ExecutionContext.evaluate (/home/myuser/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
2019-04-30T14:13:06.169Z     at ExecutionContext.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:109:23)
2019-04-30T14:13:06.170Z     at DOMWorld.evaluate (/home/myuser/node_modules/puppeteer/lib/DOMWorld.js:105:20)
2019-04-30T14:13:06.172Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-04-30T14:13:06.174Z   -- ASYNC --
2019-04-30T14:13:06.175Z     at Frame.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:108:27)
2019-04-30T14:13:06.177Z     at Page.evaluate (/home/myuser/node_modules/puppeteer/lib/Page.js:809:43)
2019-04-30T14:13:06.179Z     at Page.<anonymous> (/home/myuser/node_modules/puppeteer/lib/helper.js:109:23)
2019-04-30T14:13:06.181Z     at extractPlaceDetail (/home/myuser/src/places_crawler.js:104:43)
2019-04-30T14:13:06.182Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-04-30T14:13:08.360Z INFO: Open https://www.google.com/maps/place/?q=place_id:ChIJN6gdChTTlkcR0oV7M8qR8ZA with label: placeDetail
2019-04-30T14:13:08.395Z INFO: Extracting details from place url https://www.google.com/maps/place/?q=place_id:ChIJN6gdChTTlkcR0oV7M8qR8ZA
2019-04-30T14:13:14.230Z INFO: Infinite scroll for reviews list started, url: https://www.google.com/maps/place/Haus+Zauberfl%C3%B6te+-+Hotel+%26+Restaurant/@48.4697777,7.9449433,17z/data=!3m1!4b1!4m7!3m6!1s0x4796d3140a1da837:0x90f191ca337b85d2!8m2!3d48.4697777!4d7.947132!9m1!1b1
2019-04-30T14:13:22.494Z INFO: AutoscaledPool state {"currentConcurrency":1,"desiredConcurrency":3,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"maxOverloadedRatio":0.2,"actualRatio":0},"eventLoopInfo":{"isOverloaded":false,"maxOverloadedRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"maxOverloadedRatio":0.4,"actualRatio":0},"clientInfo":{"isOverloaded":false,"maxOverloadedRatio":0.3,"actualRatio":0}}}`

**Comment by ntmedia77654** [comment]
Could it be the German umlauts in the URL?

**Comment by drobnikj** [comment]
I found the issue. There are reviews from other sources than google, e.g. booking.
There are rating instead of starts. I fixed it. It works now.
