### ISSUE TITLE
Reviews extraction crashes after all reviews are collected

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#108]
It happens only rarely. Maybe we go over the last review page and it displays an HTML page instead? If it happens when we go over, we can easily ignore this HTML. But ideally, we want to fix the root cause as well.

```
2021-01-27T17:51:17.083Z   SyntaxError: Operation failed: Reviews extraction. Error detail: Unexpected token < in JSON at position 0
2021-01-27T17:51:17.084Z       at JSON.parse (<anonymous>)
2021-01-27T17:51:17.086Z       at stringifyGoogleXrhResponse (/home/myuser/src/utils.js:26:17)
2021-01-27T17:51:17.088Z       at parseReviewFromResponseBody (/home/myuser/src/utils.js:67:21)
2021-01-27T17:51:17.090Z       at module.exports.extractReviews (/home/myuser/src/extractors.js:367:33)
2021-01-27T17:51:17.096Z       at runMicrotasks (<anonymous>)
2021-01-27T17:51:17.098Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-27T17:51:17.100Z       at async ErrorSnapshotter.tryWithSnapshot (/home/myuser/src/error-snapshotter.js:58:20)
2021-01-27T17:51:17.101Z       at async module.exports.handlePlaceDetail (/home/myuser/src/detail_page_handle.js:89:12)
2021-01-27T17:51:17.103Z       at async handlePageFunctionExtended (/home/myuser/src/places_crawler.js:79:13)
2021-01-27T17:51:17.105Z       at async ErrorSnapshotter.tryWithSnapshot (/home/myuser/src/error-snapshotter.js:58:20)
2021-01-27T17:51:17.107Z       at async PuppeteerCrawler.handlePageFunction [as userProvidedHandler] (/home/myuser/src/places_crawler.js:165:13)
2021-01-27T17:51:17.109Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/puppeteer_crawler.js:316:13)
2021-01-27T17:51:17.111Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:381:13)
2021-01-27T17:51:17.112Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:397:13)
```

**Comment by metalwarrior665** [comment]
I cannot reproduce this now so maybe it was fixed with the review fixes.

Anyway, it should be handled gracefully now. Will reopen if it will popup again.
