### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Request is already handled!

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#135]
Happens in the scrolling code

2021-05-02T04:46:50.572Z (node:47) UnhandledPromiseRejectionWarning: Error: Request is already handled!
2021-05-02T04:46:50.574Z     at Object.exports.assert (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
2021-05-02T04:46:50.576Z     at HTTPRequest.continue (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPRequest.js:217:21)
2021-05-02T04:46:50.578Z     at /home/myuser/src/infinite_scroll.js:66:36
2021-05-02T04:46:50.579Z     at /home/myuser/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
2021-05-02T04:46:50.581Z     at Array.map (<anonymous>)
2021-05-02T04:46:50.583Z     at Object.emit (/home/myuser/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
2021-05-02T04:46:50.584Z     at Page.emit (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
2021-05-02T04:46:50.586Z     at /home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:143:100
2021-05-02T04:46:50.588Z     at /home/myuser/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
2021-05-02T04:46:50.589Z     at Array.map (<anonymous>)
2021-05-02T04:46:50.598Z     at Object.emit (/home/myuser/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
2021-05-02T04:46:50.602Z     at NetworkManager.emit (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
2021-05-02T04:46:50.610Z     at NetworkManager._onRequest

**Comment by metalwarrior665** [comment]
Didn't see this for a while, might have been transient bug in SDK

**Comment by metalwarrior665** [comment]
We removed the infinite scroll function so this cannot happen anymore
