### ISSUE TITLE
 Error: Operation failed. Error detail: Evaluation failed: TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.

### ISSUE THREAD

**Issue by pocesar** [drobnikj/crawler-google-places#136]
```
2021-05-07T03:00:56.242Z   Error: Operation failed. Error detail: Evaluation failed: TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
2021-05-07T03:00:56.244Z       at __puppeteer_evaluation_script__:2:38037
2021-05-07T03:00:56.247Z       at __puppeteer_evaluation_script__:2:220
2021-05-07T03:00:56.249Z       at __puppeteer_evaluation_script__:2:225
2021-05-07T03:00:56.252Z       at ExecutionContext._evaluateInternal (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:171:23)
2021-05-07T03:00:56.254Z       at runMicrotasks (<anonymous>)
2021-05-07T03:00:56.257Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-05-07T03:00:56.259Z       at async ExecutionContext.evaluate (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
2021-05-07T03:00:56.267Z       at async Promise.all (index 1)
2021-05-07T03:00:56.270Z       at async handlePageFunctionExtended (/home/myuser/src/places_crawler.js:33:5)
2021-05-07T03:00:56.272Z       at async ErrorSnapshotter.tryWithSnapshot (/home/myuser/src/error-snapshotter.js:58:20)
2021-05-07T03:00:56.274Z       at async PuppeteerCrawler.handlePageFunction [as userProvidedHandler] (/home/myuser/src/places_crawler.js:160:13)
2021-05-07T03:00:56.277Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/puppeteer_crawler.js:316:13)
2021-05-07T03:00:56.279Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:381:13)
2021-05-07T03:00:56.282Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:397:13)
```

just regular settings.
sample run https://my.apify.com/view/runs/19sGiTR2jTmbSqLBL

**Comment by petrfilipec** [comment]
+1, getting the same errors all the time. I need to run the actor multiple times to successfully get any results.

**Comment by metalwarrior665** [comment]
Well, this is a funny one. Injecting JQuery fails on consent screen.

**Comment by metalwarrior665** [comment]
Can you guys please test if you get the error in the latest version still? After I merged the PR that fixes the consent screen, it should hopefully resolve this as well.

**Comment by falkenbach** [comment]
Current version works fine, as you can see with debug option enabled actor forwarded to consent page and processing it wo errors, the rest of the input is the same as in original bug report https://my.apify.com/view/runs/3rkDsCAULaSAXHrrv

**Comment by metalwarrior665** [comment]
Thanks, hope this is solved for good

**Comment by beshoo** [comment]
@metalwarrior665 
Hello. 
Am having the same error over and over, I downloaded the current version of the crawler.
