### ISSUE TITLE
Navigation back from additional data sometimes doesn't find button

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#140]
We probably need to check for visibility. cc @mattiashtd . This happens only rarely.

Happened on 
https://www.google.com/maps/search/?api=1&query=london+tourist+sites&query_place_id=ChIJc2nSALkEdkgRkuoJJBfzkUI&hl=en
Which is a normal page

Maybe a bit more wait time would solve it

```
2021-05-17T12:42:02.745Z   Error: Operation failed. Error detail: Node is either not visible or not an HTMLElement
2021-05-17T12:42:02.747Z       at ElementHandle._clickablePoint (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:329:19)
2021-05-17T12:42:02.750Z       at runMicrotasks (<anonymous>)
2021-05-17T12:42:02.752Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-05-17T12:42:02.754Z       at async ElementHandle.click (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:390:26)
2021-05-17T12:42:02.756Z       at async navigationSucceeded (/home/myuser/src/extractors.js:292:13)
2021-05-17T12:42:02.759Z       at async waiter (/home/myuser/src/utils.js:246:13)
2021-05-17T12:42:02.761Z       at async navigateBack (/home/myuser/src/extractors.js:299:5)
2021-05-17T12:42:02.763Z       at async module.exports.extractAdditionalInfo (/home/myuser/src/extractors.js:230:13)
2021-05-17T12:42:02.765Z       at async module.exports.handlePlaceDetail (/home/myuser/src/detail_page_handle.js:130:42)
2021-05-17T12:42:02.769Z       at async handlePageFunctionExtended (/home/myuser/src/places_crawler.js:72:13)
2021-05-17T12:42:02.771Z       at async ErrorSnapshotter.tryWithSnapshot (/home/myuser/src/error-snapshotter.js:58:20)
2021-05-17T12:42:02.775Z       at async PuppeteerCrawler.handlePageFunction [as userProvidedHandler] (/home/myuser/src/places_crawler.js:160:13)
2021-05-17T12:42:02.777Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/puppeteer_crawler.js:316:13)
2021-05-17T12:42:02.779Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:381:13)
2021-05-17T12:42:02.781Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:397:13)
```

**Comment by metalwarrior665** [comment]
Seems it loaded some different sub-page, perhaps need to adjust selectors
https://api.apify.com/v2/key-value-stores/kCLhNej0dMl98NoKE/records/ERROR-SNAPSHOT-Node-is-either-not-visible-or-not-an-HTMLElement.jpg

**Comment by mattiashtd** [comment]
@metalwarrior665 Thank you for the info. I'm having a look at it. Would be better if it would occur more often to fix it, of course :)

**Comment by mattiashtd** [comment]
@metalwarrior665 This PR should fix it: https://github.com/drobnikj/crawler-google-places/pull/142
I could reproduce it every about 7th time when clicking the back button even more frequently first.
Afterwards I checked it with the fix about 15 times with the more frequent clicks. Then I changed back the frequency again.
So I'm quite sure it's fixed now :)

**Comment by metalwarrior665** [comment]
Amazing
