### ISSUE TITLE
Cannot read property 'name' of undefined - Docker

### ISSUE THREAD

**Issue by patrickredo** [drobnikj/crawler-google-places#154]
Docker container output this error at start:

Starting X virtual framebuffer using: Xvfb :99 -ac -screen 0 1280x720x16 -nolisten tcp
Executing main command
INFO  System info {"apifyVersion":"0.22.5","apifyClientVersion":"1.0.1","osType":"Linux","nodeVersion":"v12.18.4"}
ERROR The function passed to Apify.main() threw an exception:
  TypeError: Cannot read property 'name' of undefined
      at RequestQueueClient.get (/home/myuser/node_modules/@apify/storage-local/src/resource_clients/request_queue.js:86:30)
      at StorageManager._getOrCreateStorage (/home/myuser/node_modules/apify/build/storages/storage_manager.js:97:53)
      at StorageManager.openStorage (/home/myuser/node_modules/apify/build/storages/storage_manager.js:52:46)
      at Object.exports.openRequestQueue (/home/myuser/node_modules/apify/build/storages/request_queue.js:582:20)
      at /home/myuser/src/main.js:68:38
      at async run (/home/myuser/node_modules/apify/build/actor.js:181:13)

Image was created with default Dockerfile.

The apify_storage folder was mounted with:

/docker/gmc_input/0003494a19ca5351f99b3cad33762a2f:/home/myuser/apify_storage 

and chowned to user 999, the container is able to read input file and write to all folders. 

Tks

**Comment by metalwarrior665** [comment]
Hi @patrickredo . People rarely use this in their own Docker container so we don't have much experience with it. Have you tried any other Apify actors? This one has a bit older version so that might cause some problems with it. If you have problems with other actors, then I suggest submit an issue to https://github.com/apify/apify-js or come to discuss it to our [Discord](https://discord.com/invite/jyEM2PRvMU).

There isn't anything specific to this actor so better to solve this elsewhere.
