### ISSUE TITLE
UnhandledPromiseRejectionWarning on waitAndHandleConsentScreen

### ISSUE THREAD

**Issue by pocesar** [drobnikj/crawler-google-places#161]
Errors being thrown inside https://github.com/drobnikj/crawler-google-places/blob/409a52f19336d8ae6014b2c67e3f9559dc2cf918/src/places_crawler.js#L143-L155 are considered `UnhandledPromiseRejectionWarning` 
by default, EventEmitter does not work with async callbacks and you need to use a deferred Promise instead

```
2021-06-24T01:10:27.706Z (node:47) UnhandledPromiseRejectionWarning: Error: Waiting for consent screen timeouted after 60000ms on URL: https://www.google.com/maps/...
2021-06-24T01:10:27.708Z     at waiter (/home/myuser/src/utils.js:261:19)
2021-06-24T01:10:27.709Z     at runMicrotasks (<anonymous>)
2021-06-24T01:10:27.710Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-06-24T01:10:27.710Z     at async waitAndHandleConsentScreen (/home/myuser/src/utils.js:322:5)
2021-06-24T01:10:27.711Z     at async /home/myuser/src/places_crawler.js:150:21
2021-06-24T01:10:27.712Z (node:47) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by metalwarrior665** [comment]
Do you have any good deferred Promise example?

**Comment by pocesar** [comment]
https://github.com/pocesar/actor-facebook-scraper/blob/master/src/page.ts#L454

**Comment by pocesar** [comment]
https://github.com/pocesar/actor-facebook-scraper/blob/0cc204d8b66171a5cb1c9c444ac04944291c6cc4/src/page.ts#L454-L495
