### ISSUE TITLE
How to run this project without apify 

### ISSUE THREAD

**Issue by beshoo** [drobnikj/crawler-google-places#183]
Dear all. 
I want to run this project on my Linux server and Windows PC, I have a node.
But I don't want to use apify servers or proxy altogether. 
PS: I have my own proxy list, how can I tell the "crawler-google-places" to chose a random proxy on each request.
Is "crawler-google-places" headless software?

So how to install this grat project, and what are the commands I need to pass, and how to use my own proxy list?

Thank you so much.

**Comment by pocesar** [comment]
follow the instructions here https://sdk.apify.com/docs/guides/getting-started
use `npm i` and `apify init` after checking out the code here. you don't need to use `apify login` when using `apify run --purge`. place your proxy settings into `apify_storage/key_value_stores/default/INPUT.json`

**Comment by beshoo** [comment]
@pocesar 
Thanks,
Well.
I did the following :
1- npm install -g apify-cli 
2- gh repo clone drobnikj/crawler-google-places
3- cd crawler-google-places
4- 
```
E:\googlec\crawler-google-places>apify run -p
Info: All default local stores were purged.
Warning: You are not logged in with your Apify Account. Some features like Apify Proxy will not work. Call "apify login" to fix that.
Run: npm.cmd start

> crawler-google-places@1.0.0 start E:\googlec\crawler-google-places
> node ./src/main.js

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'apify'
Require stack:
- E:\googlec\crawler-google-places\src\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (E:\googlec\crawler-google-places\src\main.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'E:\\googlec\\crawler-google-places\\src\\main.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crawler-google-places@1.0.0 start: `node ./src/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crawler-google-places@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\beshoo\AppData\Roaming\npm-cache\_logs\2021-09-12T23_04_06_908Z-debug.log
Error: npm.cmd exited with code 1

E:\googlec\crawler-google-places>
E:\googlec\crawler-google-places>

```

Why is that ?

**Comment by beshoo** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.17.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle crawler-google-places@1.0.0~prestart: crawler-google-places@1.0.0
6 info lifecycle crawler-google-places@1.0.0~start: crawler-google-places@1.0.0
7 verbose lifecycle crawler-google-places@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle crawler-google-places@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\googlec\crawler-google-places\node_modules\.bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Windows Resource Kits\Tools\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;E:\Go\bin;C:\Program Files\Git\cmd;G:\xampp\php;C:\composer;C:\Program Files\nodejs\;C:\Users\beshoo\AppData\Local\Microsoft\WindowsApps;;C:\Users\beshoo\AppData\Local\Programs\Fiddler;C:\Users\beshoo\go\bin;C:\Users\beshoo\AppData\Roaming\Composer\vendor\bin;C:\Users\beshoo\AppData\Roaming\npm;C:\Program Files (x86)\GitHub CLI\
9 verbose lifecycle crawler-google-places@1.0.0~start: CWD: E:\googlec\crawler-google-places
10 silly lifecycle crawler-google-places@1.0.0~start: Args: [ '/d /s /c', 'node ./src/main.js' ]
11 silly lifecycle crawler-google-places@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle crawler-google-places@1.0.0~start: Failed to exec start script
13 verbose stack Error: crawler-google-places@1.0.0 start: `node ./src/main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid crawler-google-places@1.0.0
15 verbose cwd E:\googlec\crawler-google-places
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.17.6
19 verbose npm  v6.14.15
20 error code ELIFECYCLE
21 error errno 1
22 error crawler-google-places@1.0.0 start: `node ./src/main.js`
22 error Exit status 1
23 error Failed at the crawler-google-places@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by beshoo** [comment]
Solved 
**npm install apify**
