### ISSUE TITLE
Error: net::ERR_NO_SUPPORTED_PROXIES

### ISSUE THREAD

**Issue by beshoo** [drobnikj/crawler-google-places#187]
Dear all. 
Am using Opera proxy which is available here:
https://github.com/Snawoot/opera-proxy

```
  proxyConfig: {
    useApifyProxy: false,
  
    proxyUrls: [
      'http://loalhost:18080'
    ]
  }
```

apify return 

```
ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/@33.52022999984266,36.28383016301731,16z/search?hl=en","retryCount":1,"id":"EwegtwQajboMtYa"}
  Error: net::ERR_NO_SUPPORTED_PROXIES at https://www.google.com/maps/@33.52022999984266,36.28383016301731,16z/search?hl=en
      at navigate (C:\Users\beshoo\crawler-google-places\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:115:23)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async FrameManager.navigateFrame (C:\Users\beshoo\crawler-google-places\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:90:21)
      at async Frame.goto (C:\Users\beshoo\crawler-google-places\node_modules\puppeteer\lib\cjs\puppeteer\common\FrameManager.js:416:16)
      at async Page.goto (C:\Users\beshoo\crawler-google-places\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1149:16)
      at async PuppeteerCrawler._handleNavigation (C:\Users\beshoo\crawler-google-places\node_modules\apify\build\crawlers\browser_crawler.js:361:40)
      at async PuppeteerCrawler._handleRequestFunction (C:\Users\beshoo\crawler-google-places\node_modules\apify\build\crawlers\browser_crawler.js:316:13)
      at async PuppeteerCrawler._runTaskFunction (C:\Users\beshoo\crawler-google-places\node_modules\apify\build\crawlers\basic_crawler.js:425:13)
      at async AutoscaledPool._maybeRunTask (C:\Users\beshoo\crawler-google-places\node_modules\apify\build\autoscaling\autoscaled_pool.js:408:17)
```

while I can curl "`https://www.google.com/maps/@33.52022999984266,36.28383016301731,16z/search?hl=en`"  with the same proxy IP and I can see the output.

and I can browse to google map via chrome using the proxy 
![image](https://user-images.githubusercontent.com/4635115/133179561-63436802-26ec-41c2-bc0f-641658d53d69.png)

Please advice!

**Comment by pocesar** [comment]
it's a puppeteer limitation when using proxies from other providers (Apify proxy deals with it for you). https://github.com/puppeteer/puppeteer/issues/2234

**Comment by beshoo** [comment]
It is http://localhost:18080

Is it the problem with the ip addresses it self?
Using npm /proxy-chain/ will help or not?

Thanks for the help...

**Comment by metalwarrior665** [comment]
Unfortunately, I think proxies without authentication are not supported

**Comment by beshoo** [comment]
Great, yu just solved my problem...
I pass this ***@***.***:18080 to Oprah proxy, and it
works :)
