### ISSUE TITLE
Problems with arabic

### ISSUE THREAD

**Issue by pocesar** [drobnikj/crawler-google-places#189]
this input is giving a constant error with "Operation failed. Error detail: Node is either not visible or not an HTMLElement"

<details>
<summary>INPUT.json</summary>

```json
{
  "searchStringsArray": [
    "مطاعم سمك في جدة"
  ],
  "maxCrawledPlaces": 6000,
  "maxCrawledPlacesPerSearch": 6000,
  "language": "ar",
  "maxReviews": 40,
  "maxImages": 3,
  "includeHistogram": false,
  "includeOpeningHours": false,
  "includePeopleAlsoSearch": false,
  "additionalInfo": true,
  "reviewsSort": "mostRelevant",
  "reviewsTranslation": "onlyOriginal",
  "exportPlaceUrls": false,
  "city": "jeddah",
  "proxyConfig": {
    "useApifyProxy": true
  },
  "useChrome": true,
  "debug": false,
  "useStealth": false,
  "scrapeReviewerName": false,
  "scrapeReviewerId": false,
  "scrapeReviewerUrl": false,
  "scrapeReviewId": false,
  "scrapeReviewUrl": false,
  "scrapeResponseFromOwnerText": false,
  "zoom": 12,
  "maxConcurrency": 100,
  "maxPageRetries": 6,
  "pageLoadTimeoutSec": 60,
  "maxPagesPerBrowser": 1
}
```
</details>

<details>
<summary>Stack trace</summary>

```
2021-09-14T17:23:04.503Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/@21.5810088,39.16536119999999,12z/search?hl=ar","retryCount":1,"id":"dg3do7N9mvEJubR"}
2021-09-14T17:23:04.509Z   Error: Operation failed. Error detail: Node is either not visible or not an HTMLElement
2021-09-14T17:23:04.509Z       at ElementHandle.clickablePoint (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:339:19)
2021-09-14T17:23:04.510Z       at runMicrotasks (<anonymous>)
2021-09-14T17:23:04.512Z       at processTicksAndRejections (internal/process/task_queues.js:95:5)
2021-09-14T17:23:04.513Z       at async ElementHandle.click (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:392:26)
2021-09-14T17:23:04.514Z       at async DOMWorld.click (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:278:9)
2021-09-14T17:23:04.515Z       at async module.exports.enqueueAllPlaceDetails (/home/myuser/src/enqueue_places.js:206:5)
2021-09-14T17:23:04.516Z       at async ErrorSnapshotter.tryWithSnapshot (/home/myuser/src/error-snapshotter.js:58:20)
2021-09-14T17:23:04.517Z       at async handlePageFunctionExtended (/home/myuser/src/places_crawler.js:55:13)
2021-09-14T17:23:04.518Z       at async ErrorSnapshotter.tryWithSnapshot (/home/myuser/src/error-snapshotter.js:58:20)
2021-09-14T17:23:04.519Z       at async PuppeteerCrawler.handlePageFunction (/home/myuser/src/places_crawler.js:155:13)
```
</details>

**Comment by beshoo** [comment]
Same Here!

**Comment by metalwarrior665** [comment]
This is really weird, it always works locally, never on platform. Probably something with browser config?

**Comment by tmleeek** [comment]
hello guys , any updates

**Comment by tmleeek** [comment]
Hello guys , please fix it or give us a solution for this  .

**Comment by tmleeek** [comment]
no one is helping here the thread is dead

**Comment by beshoo** [comment]
Arabic search is fine. I just test it

**Comment by tmleeek** [comment]
@beshoo can you please give me your input its still not working with me

**Comment by beshoo** [comment]
> @beshoo can you please give me your input its still not working with me


```
{
  searchStringsArray: [ 'بقالية' ],
  country: 'Syria',
  city: 'Damascus',
  county: '',
  postalCode:'',
  maxCrawledPlaces: 99999,
  maxCrawledPlacesPerSearch: 1000,
  maxReviews: 20,
  language: 'en',
  maxImages: 1,
  includeHistogram: true,
  includeOpeningHours: true,
  includePeopleAlsoSearch: false,
  additionalInfo: false,
  reviewsSort: 'mostRelevant',
  reviewsTranslation: 'onlyTranslated',
  exportPlaceUrls: false,
  zoom: 17,
  maxAutomaticZoomOut: 13,
  
  proxyConfig: {
    useApifyProxy: false,
  },
      maxConcurrency: 10,
      maxPageRetries: 2,
      pageLoadTimeoutSec: 60,
      maxPagesPerBrowser: 2,
      useChrome: false,
      useStealth: false,
      scrapeReviewerName: true,
      scrapeReviewerId: true,
      scrapeReviewerUrl: true,
      scrapeReviewId: true,
      scrapeReviewUrl: true,
      scrapeReviewerName:true,
      scrapeResponseFromOwnerText: true,
      debug:false,
};

```

**Comment by tmleeek** [comment]
i do not think arabic working any more even old builds , am i wrong ? @beshoo

**Comment by beshoo** [comment]
It is working just fine.

Regard

**Comment by beshoo** [comment]
@tmleeek am not sure if it related to the unicode, are you sure that input is utf-8?

Please paste the output logs...

Regard

**Comment by tmleeek** [comment]
attached input and data set please notice that reviews come in english language , i tried also original only , and get same english content 
i need arabic reviews 
[dataset.txt](https://github.com/drobnikj/crawler-google-places/files/7251357/dataset.txt)
[INPUT.txt](https://github.com/drobnikj/crawler-google-places/files/7251363/INPUT.txt)

**Comment by tmleeek** [comment]
@beshoo i wonder if you check the data i share , and @metalwarrior665 it have been 2 weeks , i wonder if you will issue a fix

**Comment by metalwarrior665** [comment]
@pocesar Do you remember if we fixed this? :)

**Comment by pocesar** [comment]
@metalwarrior665 yeah, should be fixed for RTL, but the string for opening hours is returning the wrong part, since the comma is at the other side 😄
