### ISSUE TITLE
Google block even while using rotation proxy

### ISSUE THREAD

**Issue by beshoo** [drobnikj/crawler-google-places#195]
Hi,
while am using the crawler, it works just fine but suddenly I start getting the following messages
```
Line 543:   Error: Request blocked - received 429 status code.
Line 2: (node:1) UnhandledPromiseRejectionWarning: Error: Response body is unavailable for redirect responses
	Line 14: (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
	Line 16: (node:1) UnhandledPromiseRejectionWarning: Error: Response body is unavailable for redirect responses
	Line 27: (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
	Line 28: (node:1) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
	Line 34: (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
	Line 35: (node:1) UnhandledPromiseRejectionWarning: Error: Response body is unavailable for redirect responses

```

Now, am using docker container to run "crawler-google-places", and I am setting a global proxy to the container which I can change while the crawler is working,

I changed the proxy to another proxy while the crawler is working. but the same thing, the error keeps appearing in the log.
if I kill the processes and restart it, the problem will disappear for a while, then it will appear.

What do you think the problem is?

![image](https://user-images.githubusercontent.com/4635115/134179526-b880b0f7-9be2-4ef2-a12b-a1c6bc84fd97.png)

Do you thing if I disable **persistCookiesPerSession** may solve the problem?

**Comment by metalwarrior665** [comment]
On Apify we never get blocked like this so it is probably your bad proxy. The unhandled rejections are a problem so will look into that,

**Comment by beshoo** [comment]
Am not sure if you fully read my issue.
Am saying that I changed the proxy while the process is running, and the same error keeps appearing
so the question is google block the Cookies?

is using persistCookiesPerSession may solve this?

Reagrds

**Comment by metalwarrior665** [comment]
Where exactly did this happen? We run millions of pages with hundreds of different setups and I never saw this error.

**Comment by pocesar** [comment]
you're using Node 15+, there's no support for it for this scraper yet.

**Comment by beshoo** [comment]
@pocesar  
Am using **https://github.com/drobnikj/crawler-google-places/blob/master/Dockerfile**
and the problem is not related to the node in any how!

**Comment by beshoo** [comment]
I tested the **brightdata.com** proxy service for the residential plan.
after 3 min of successful scraping, I start getting these errors... all about `Response body is unavailable for redirect responses!`
```
INFO  [SEARCH]: Start enqueuing places details for search --- مطاعم https://www.google.com/maps/@33.50411887519665,36.27310048094121,17z/search?hl=en
(node:1) UnhandledPromiseRejectionWarning: Error: Response body is unavailable for redirect responses
    at NetworkManager._handleRequestRedirect (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/NetworkManager.js:289:31)
    at NetworkManager._onRequest (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/NetworkManager.js:264:22)
    at NetworkManager._onRequestWillBeSent (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/NetworkManager.js:205:14)
    at /home/myuser/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (/home/myuser/node_modules/puppeteer/lib/cjs/vendor/mitt/src/index.js:51:43)
    at CDPSession.emit (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/EventEmitter.js:72:22)
    at CDPSession._onMessage (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:234:18)
    at Connection._onMessage (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:111:25)
    at WebSocket.<anonymous> (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:13:32)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4752)
(node:1) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at module.exports.parseSearchPlacesResponseBody (/home/myuser/src/extractors.js:59:29)
    at /home/myuser/src/enqueue_places.js:48:42
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```
and here is my input
```

{
  searchStringsArray: ['مطاعم'],
  country: 'saudi arabia',
  city: 'jeddah',
  county: '',
  postalCode:'',
  maxCrawledPlaces: 10000,
  maxCrawledPlacesPerSearch: 1000,
  maxReviews: input_maxReviews,
  language: 'en',
  maxImages: 1,
  includeHistogram: true,
  includeOpeningHours: true,
  includePeopleAlsoSearch: false,
  additionalInfo: false,
  reviewsSort: 'mostRelevant',
  reviewsTranslation: 'onlyTranslated',
  exportPlaceUrls: false,
  zoom: 17,
  maxAutomaticZoomOut: 13,
  
  proxyConfig: {
    useApifyProxy: false,
    proxyUrls: [
      'http://username:password@brightdata.com'
    ]
  },
      maxConcurrency: 20,
      maxPageRetries: 2,
      pageLoadTimeoutSec: 60,
      maxPagesPerBrowser: 10,
      useChrome: false,
      useStealth: false,
      scrapeReviewerName: true,
      scrapeReviewerId: true,
      scrapeReviewerUrl: true,
      scrapeReviewId: true,
      scrapeReviewUrl: true,
      scrapeReviewerName:true,
      scrapeResponseFromOwnerText: true,
      debug:false,
};
```

**Comment by beshoo** [comment]
I think this problem is related to "maxConcurrency", when I set maxConcurrency on "2", this problem never appears again.
