### ISSUE TITLE
waiting for selector `.section-hero-header-image-hero-container` failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by beshoo** [drobnikj/crawler-google-places#196]
While am scarping for 3 hours, I start getting this error? what is the problem

```
TimeoutError: Operation failed: Image extraction. Error detail: waiting for selector `.section-hero-header-image-hero-container` failed: timeout 30000ms exceeded
      at new WaitTask (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34)
      at DOMWorld.waitForSelectorInPage (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26)
      at Object.internalHandler.waitFor (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
      at DOMWorld.waitForSelector (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29)
      at Frame.waitForSelector (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51)
      at Page.waitForSelector (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2252:33)
      at module.exports.extractImages (/home/myuser/src/extractors.js:598:34)
      at detail.imageUrls.errorSnapshotter.tryWithSnapshot.name (/home/myuser/src/detail_page_handle.js:186:25)
      at ErrorSnapshotter.tryWithSnapshot (/home/myuser/src/error-snapshotter.js:58:26)
      at module.exports.handlePlaceDetail (/home/myuser/src/detail_page_handle.js:184:43)

```

**Comment by beshoo** [comment]
Setting `maxImages:0` fixes the problem but now we scrape with no image.

**Comment by beshoo** [comment]
Why does the crawler save the error as a JSON file within the address?
while debug is false.
**000000003.json**
```
{
"#url": "https://www.google.com/maps/search/?api=1&query=%D8%AF%D8%AC%D8%A7%D8%AC+%D8%A8%D8%B1%D9%88%D8%B3%D8%AA%D8%AF&query_place_id=ChIJw7RvrcmtJhURnoNb0upgYY8&hl=en",
"#succeeded": false,
"#errors": [
"TimeoutError: Operation failed: Image extraction. Error detail: waiting for selector `.section-hero-header-image-hero-container` failed: timeout 30000ms exceeded at new WaitTask (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34) at DOMWorld.waitForSelectorInPage (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26) at Object.internalHandler.waitFor (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77) at DOMWorld.waitForSelector (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29) at Frame.waitForSelector (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51) at Page.waitForSelector (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2252:33) at module.exports.extractImages (/home/myuser/src/extractors.js:598:34) at detail.imageUrls.errorSnapshotter.tryWithSnapshot.name (/home/myuser/src/detail_page_handle.js:186:25) at ErrorSnapshotter.tryWithSnapshot (/home/myuser/src/error-snapshotter.js:58:26) at module.exports.handlePlaceDetail (/home/myuser/src/detail_page_handle.js:184:43)"
],
"#debugInfo": {
"requestId": "BSdI6ZdHlYAp7aq",
"url": "https://www.google.com/maps/search/?api=1&query=%D8%AF%D8%AC%D8%A7%D8%AC+%D8%A8%D8%B1%D9%88%D8%B3%D8%AA%D8%AF&query_place_id=ChIJw7RvrcmtJhURnoNb0upgYY8&hl=en",
"loadedUrl": "https://consent.google.com/m?continue=https://www.google.com/maps/search/?api%3D1%26query%3D%25D8%25AF%25D8%25AC%25D8%25A7%25D8%25AC%2B%25D8%25A8%25D8%25B1%25D9%2588%25D8%25B3%25D8%25AA%25D8%25AF%26query_place_id%3DChIJw7RvrcmtJhURnoNb0upgYY8%26hl%3Den&gl=DE&m=0&pc=m&hl=en&src=1",
"method": "GET",
"retryCount": 0,
"errorMessages": [
"TimeoutError: Operation failed: Image extraction. Error detail: waiting for selector `.section-hero-header-image-hero-container` failed: timeout 30000ms exceeded at new WaitTask (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:509:34) at DOMWorld.waitForSelectorInPage (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:420:26) at Object.internalHandler.waitFor (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77) at DOMWorld.waitForSelector (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:313:29) at Frame.waitForSelector (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:841:51) at Page.waitForSelector (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2252:33) at module.exports.extractImages (/home/myuser/src/extractors.js:598:34) at detail.imageUrls.errorSnapshotter.tryWithSnapshot.name (/home/myuser/src/detail_page_handle.js:186:25) at ErrorSnapshotter.tryWithSnapshot (/home/myuser/src/error-snapshotter.js:58:26) at module.exports.handlePlaceDetail (/home/myuser/src/detail_page_handle.js:184:43)"
]
},
"#debugFiles": {
"html": "https://api.apify.com/v2/key-value-stores/default/records/BSdI6ZdHlYAp7aq.html",
"screen": "https://api.apify.com/v2/key-value-stores/default/records/BSdI6ZdHlYAp7aq.png"
}
}
```

**Comment by metalwarrior665** [comment]
Thank you for the PR. I also made this selector optional so next time it won't crash everything.
