### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID when using with Apify

### ISSUE THREAD

**Issue by hassanj-576** [drobnikj/crawler-google-places#232]
I am trying to run the actor with Apify but i am getting `ERR_CERT_AUTHORITY_INVALID` error.
I am using United States Proxy, I even tried using Pakistan (the Country where i am from) but getting the same error.
Any idea what's causing certificate validation to fail? How can it be resolved 
Here is a log

```
2022-01-19T12:56:02.535Z ACTOR: Pulling Docker image from repository.
2022-01-19T12:56:02.615Z ACTOR: Creating Docker container.
2022-01-19T12:56:02.712Z ACTOR: Starting Docker container.
2022-01-19T12:56:06.789Z INFO  System info {"apifyVersion":"1.3.4","apifyClientVersion":"1.4.2","osType":"Linux","nodeVersion":"v14.18.2"}
2022-01-19T12:56:07.276Z INFO  Prepared 1 Start URLs (showing max 10):
2022-01-19T12:56:07.279Z [
2022-01-19T12:56:07.281Z   'https://www.google.com/maps/place/Axis+Stem+Cell+Institute/@47.644197999999996,-122.1994759,14z/data=!4m5!3m4!1s0x54906d68f2a2754f:0x1369aeeffd2f5f99!8m2!3d47.644197999999996!4d-122.1994759'
2022-01-19T12:56:07.282Z ]
2022-01-19T12:56:08.922Z INFO  Full list of Start URLs is available on link: https://api.apify.com/v2/key-value-stores/KoFbecNLCZLlUgJaz/records/START-REQUESTS?disableRedirect=true
2022-01-19T12:56:10.725Z INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
2022-01-19T12:56:11.413Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/place/Axis+Stem+Cell+Institute/@47.644197999999996,-122.1994759,14z/data=!4m5!3m4!1s0x54906d68f2a2754f:0x1369aeeffd2f5f99!8m2!3d47.644197999999996!4d-122.1994759?hl=en","retryCount":1,"id":"nhYxhPNMJJgq9qk"}
2022-01-19T12:56:11.415Z   Error: net::ERR_CERT_AUTHORITY_INVALID at https://www.google.com/maps/place/Axis+Stem+Cell+Institute/@47.644197999999996,-122.1994759,14z/data=!4m5!3m4!1s0x54906d68f2a2754f:0x1369aeeffd2f5f99!8m2!3d47.644197999999996!4d-122.1994759?hl=en
2022-01-19T12:56:11.417Z       at navigate (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:116:23)
2022-01-19T12:56:11.419Z       at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-01-19T12:56:11.421Z       at async FrameManager.navigateFrame (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:91:21)
2022-01-19T12:56:11.423Z       at async Frame.goto (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
2022-01-19T12:56:11.425Z       at async Page.goto (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1156:16)
2022-01-19T12:56:11.427Z       at async PuppeteerCrawler._handleNavigation (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:361:40)
2022-01-19T12:56:11.428Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:316:13)
2022-01-19T12:56:11.430Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:425:13)
2022-01-19T12:56:11.432Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:408:17)
2022-01-19T12:56:15.901Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/place/Axis+Stem+Cell+Institute/@47.644197999999996,-122.1994759,14z/data=!4m5!3m4!1s0x54906d68f2a2754f:0x1369aeeffd2f5f99!8m2!3d47.644197999999996!4d-122.1994759?hl=en","retryCount":2,"id":"nhYxhPNMJJgq9qk"}
2022-01-19T12:56:15.903Z   Error: net::ERR_CERT_AUTHORITY_INVALID at https://www.google.com/maps/place/Axis+Stem+Cell+Institute/@47.644197999999996,-122.1994759,14z/data=!4m5!3m4!1s0x54906d68f2a2754f:0x1369aeeffd2f5f99!8m2!3d47.644197999999996!4d-122.1994759?hl=en
2022-01-19T12:56:15.905Z       at navigate (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:116:23)
2022-01-19T12:56:15.906Z       at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-01-19T12:56:15.907Z       at async FrameManager.navigateFrame (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:91:21)
2022-01-19T12:56:15.909Z       at async Frame.goto (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
2022-01-19T12:56:15.910Z       at async Page.goto (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1156:16)
2022-01-19T12:56:15.911Z       at async PuppeteerCrawler._handleNavigation (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:361:40)
2022-01-19T12:56:15.913Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:316:13)
2022-01-19T12:56:15.914Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:425:13)
2022-01-19T12:56:15.915Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:408:17)
2022-01-19T12:56:19.738Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/place/Axis+Stem+Cell+Institute/@47.644197999999996,-122.1994759,14z/data=!4m5!3m4!1s0x54906d68f2a2754f:0x1369aeeffd2f5f99!8m2!3d47.644197999999996!4d-122.1994759?hl=en","retryCount":3,"id":"nhYxhPNMJJgq9qk"}
2022-01-19T12:56:19.741Z   Error: net::ERR_CERT_AUTHORITY_INVALID at https://www.google.com/maps/place/Axis+Stem+Cell+Institute/@47.644197999999996,-122.1994759,14z/data=!4m5!3m4!1s0x54906d68f2a2754f:0x1369aeeffd2f5f99!8m2!3d47.644197999999996!4d-122.1994759?hl=en
2022-01-19T12:56:19.743Z       at navigate (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:116:23)
2022-01-19T12:56:19.745Z       at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-01-19T12:56:19.746Z       at async FrameManager.navigateFrame (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:91:21)
2022-01-19T12:56:19.748Z       at async Frame.goto (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:16)
2022-01-19T12:56:19.751Z       at async Page.goto (/home/myuser/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1156:16)
2022-01-19T12:56:19.753Z       at async PuppeteerCrawler._handleNavigation (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:361:40)
2022-01-19T12:56:19.754Z       at async PuppeteerCrawler._handleRequestFunction (/home/myuser/node_modules/apify/build/crawlers/browser_crawler.js:316:13)
2022-01-19T12:56:19.756Z       at async PuppeteerCrawler._runTaskFunction (/home/myuser/node_modules/apify/build/crawlers/basic_crawler.js:425:13)
2022-01-19T12:56:19.757Z       at async AutoscaledPool._maybeRunTask (/home/myuser/node_modules/apify/build/autoscaling/autoscaled_pool.js:408:17)
```

**Comment by hassanj-576** [comment]
Sorry, silly mistake on my end, figured it out
