### ISSUE TITLE
Error: Protocol error (Network.getResponseBody): Target closed

### ISSUE THREAD

**Issue by deweydb** [drobnikj/crawler-google-places#246]
```
/Scrape/crawler-google-places/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208
            this._callbacks.set(id, { resolve, reject, error: new Error(), method });
                                                              ^

Error: Protocol error (Network.getResponseBody): Target closed.
    at /Scrape/crawler-google-places/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/Scrape/crawler-google-places/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at /Scrape/crawler-google-places/node_modules/puppeteer/lib/cjs/puppeteer/common/HTTPResponse.js:99:53
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Scrape/crawler-google-places/src/enqueue_places.js:53:30
    at async /Scrape/crawler-google-places/src/enqueue_places.js:217:42
Error: npm exited with code 1
```

Is this a bug, or just google getting mad and blocking the connection? The script seems to randomly crash like this.

**Comment by pocesar** [comment]
@deweydb please use Node 14 when using this scraper locally. Node 16 support will come eventually

**Comment by deweydb** [comment]
Awesome thanks @pocesar!
For others who find this this is what i did to fix this on Mac OS:
```
brew install node@14
nano ~/.zshrc
# or nano ~/.bash_profile depending on what shell you use
# add these two lines to toggle between node versions to the bottom of the file
alias node16='export PATH="/usr/local/bin:/usr/local/opt/node@16/bin:$PATH"; node -v'
alias node14='export PATH="/usr/local/opt/node@14/bin:$PATH"; node -v'
# save the file. and reload the shell or you can also load it again with `source ~/.zshrc`
# switch to node 14
node14
# delete the old node_modules folder from the project
cd /Scrape/crawler-google-places
rm -Rf node_modules
# reinstall under node14
npm install
# and now 
apify run --purge
```
