### ISSUE TITLE
SOLVED: Is this lib works on linux? Error detail: waiting for selector `#searchboxinput`

### ISSUE THREAD

**Issue by beshoo** [drobnikj/crawler-google-places#283]
While resting on my local windows PC, the lib works as expected, once I decide to move it to the Linux box problems started 

```
INFO  System info {"apifyVersion":"2.3.2","apifyClientVersion":"2.6.0","osType":"Linux","nodeVersion":"v16.14.0"}
WARN  Neither APIFY_LOCAL_STORAGE_DIR nor APIFY_TOKEN environment variable is set, defaulting to APIFY_LOCAL_STORAGE_DIR="/download/google_place/src/apify_storage"
WARN  The following Key-value store directory contains a previous state:
      /download/google_place/src/apify_storage/key_value_stores/default
      If you did not intend to persist the state - please clear the respective directory and re-start the actor.
WARN  The following Request queue directory contains a previous state:
      /download/google_place/src/apify_storage/request_queues/default
      If you did not intend to persist the state - please clear the respective directory and re-start the actor.
INFO  Using zoom 16 to define the search
WARN  Actor was restarted, skipping search step because it was already done...
INFO  FingerprintInjector: Successfully initialized.
DEBUG PuppeteerCrawler:SessionPool: Recreating state from KeyValueStore {"persistStateKey":"SDK_SESSION_POOL_STATE"}
DEBUG PuppeteerCrawler:SessionPool: 0 active sessions loaded from KeyValueStore
DEBUG Statistics: Recreating state from KeyValueStore {"persistStateKey":"SDK_CRAWLER_STATISTICS_0"}
DEBUG Statistics: Loaded from KeyValueStore
INFO  PuppeteerCrawler:AutoscaledPool:Snapshotter: Setting max memory of this run to 32184 MB. Use the APIFY_MEMORY_MBYTES environment variable to override it.
DEBUG PuppeteerCrawler:AutoscaledPool: scaling up {"oldConcurrency":1,"newConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.6,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}
DEBUG PuppeteerCrawler:SessionPool: Created new Session - session_6FajbMAeyH
DEBUG PuppeteerCrawler:SessionPool: Created new Session - session_PDs7bs7aTO
DEBUG PuppeteerCrawler:SessionPool: Created new Session - session_oxzYIFmsFh
DEBUG FingerprintInjector: Using fingerprint {"fingerprint":{"screen":{"availHeight":1920,"availWidth":1053,"pixelDepth":24,"height":1920,"width":1080},"webGl":{"vendor":"Google Inc. (NVIDIA Corporation)","renderer":"ANGLE (NVIDIA Corporation, GeForce GTX 1050/PCIe/SSE2, OpenGL 4.5.0 NVIDIA 460.73.01)"},"audioCodecs":{"ogg":"probably","mp3":"probably","wav":"probably","m4a":"maybe","aac":"probably"},"videoCodecs":{"ogg":"probably","h264":"probably","webm":"probably"},"pluginsData":{"mimeTypes":["~~application/pdf~~pdf","Portable Document Format~~application/x-google-chrome-pdf~~pdf","Native Client Executable~~application/x-nacl~~","Portable Native Client Executable~~application/x-pnacl~~"],"plugins":["[object]","[object]","[object]"]},"navigator":{"cookieEnabled":true,"doNotTrack":"1","language":"en-US","languages":["en-US"],"platform":"Linux x86_64","deviceMemory":8,"hardwareConcurrency":4,"productSub":"20030107","vendor":"Google Inc.","maxTouchPoints":0},"batteryData":{"level":0.25,"chargingTime":322,"dischargingTime":null},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"}}
DEBUG PuppeteerCrawler:SessionPool: Created new Session - session_nU1hSt0h6g
DEBUG FingerprintInjector: Using fingerprint {"fingerprint":{"screen":{"availHeight":1920,"availWidth":1053,"pixelDepth":24,"height":1920,"width":1080},"webGl":{"vendor":"Google Inc. (NVIDIA Corporation)","renderer":"ANGLE (NVIDIA Corporation, GeForce GTX 1050/PCIe/SSE2, OpenGL 4.5.0 NVIDIA 460.73.01)"},"audioCodecs":{"ogg":"probably","mp3":"probably","wav":"probably","m4a":"maybe","aac":"probably"},"videoCodecs":{"ogg":"probably","h264":"probably","webm":"probably"},"pluginsData":{"mimeTypes":["~~application/pdf~~pdf","Portable Document Format~~application/x-google-chrome-pdf~~pdf","Native Client Executable~~application/x-nacl~~","Portable Native Client Executable~~application/x-pnacl~~"],"plugins":["[object]","[object]","[object]"]},"navigator":{"cookieEnabled":true,"doNotTrack":"1","language":"en-US","languages":["en-US"],"platform":"Linux x86_64","deviceMemory":8,"hardwareConcurrency":4,"productSub":"20030107","vendor":"Google Inc.","maxTouchPoints":0},"batteryData":{"level":0.25,"chargingTime":322,"dischargingTime":null},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"}}
INFO  [SEARCH]: Start enqueuing places details for search --- Restaurant https://www.google.com/maps/@41.113068451104425,-123.75331523555192,16z/search?hl=en
INFO  [SEARCH]: Start enqueuing places details for search --- Restaurant https://www.google.com/maps/@41.125837743965235,-123.75331523555192,16z/search?hl=en
ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/@41.113068451104425,-123.75331523555192,16z/search?hl=en","retryCount":1,"id":"ex44QQZ6o0eKXdI"}
  TimeoutError: Operation failed. Error detail: waiting for selector `#searchboxinput` failed: timeout 15000ms exceeded
      at new WaitTask (/download/google_place/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34)
      at DOMWorld.waitForSelectorInPage (/download/google_place/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:432:26)
      at Object.internalHandler.waitFor (/download/google_place/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
      at DOMWorld.waitForSelector (/download/google_place/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:323:29)
      at Frame.waitForSelector (/download/google_place/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:942:51)
      at Page.waitForSelector (/download/google_place/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2370:33)
      at module.exports.enqueueAllPlaceDetails (/download/google_place/src/enqueue_places.js:280:20)
      at /download/google_place/src/places_crawler.js:57:29
      at ErrorSnapshotter.tryWithSnapshot (/download/google_place/src/error-snapshotter.js:59:26)
      at handlePageFunctionExtended (/download/google_place/src/places_crawler.js:55:36)
DEBUG PuppeteerCrawler:SessionPool: Created new Session - session_jdIPtbKbdQ
DEBUG PuppeteerCrawler:SessionPool: Created new Session - session_oPiB5y0nOd

```
Input
```

{
    //const input = /** @type {typedefs.Input} */ (await Apify.getInput());
    const input = {
    "searchStringsArray": [
        "Restaurant"
    ],
    "country": "USA",
    "state": "california",
    "city": "",
    "county": "",
    "postalCode": "",
    "maxCrawledPlaces": 1000,
    "maxCrawledPlacesPerSearch": 10000,
    "maxReviews": 30,
    "language": "en",
    "maxImages": 3,
    "includeHistogram": false,
    "includeOpeningHours": false,
    "includePeopleAlsoSearch": false,
    "additionalInfo": false,
    "reviewsSort": "newest",
    "reviewsTranslation": "originalAndTranslated",
    "exportPlaceUrls": false,
    "zoom": 16,
    "maxAutomaticZoomOut": 5,
    "maxConcurrency": 2,
    "maxPageRetries": 3,
    "pageLoadTimeoutSec": 60,
    "maxPagesPerBrowser": 1,
    "scrapeReviewerName": false,
    "scrapeReviewerId": false,
    "scrapeReviewerUrl": false,
    "scrapeReviewId": false,
    "scrapeReviewUrl": false,
    "scrapeResponseFromOwnerText": false,
    "debug": true,
	
    "type": "Polygon",
    "coordinates": [
        [
            [
                -120.6353931,
                35.1344599
            ],
            [
                -120.6355648,
                35.1277211
            ],
            [
                -120.6336765,
                35.1201393
            ],
            [
                -120.6329898,
                35.1142419
            ],
            [
                -120.6302433,
                35.1038501
            ],
            [
                -120.6249218,
                35.0999178
            ],
            [
                -120.6189136,
                35.0972493
            ],
            [
                -120.6077556,
                35.0951425
            ],
            [
                -120.5983142,
                35.095283
            ],
            [
                -120.5909328,
                35.10062
            ],
            [
                -120.5902462,
                35.1082036
            ],
            [
                -120.5869846,
                35.114944
            ],
            [
                -120.5809764,
                35.1212626
            ],
            [
                -120.5663852,
                35.1141015
            ],
            [
                -120.5521373,
                35.1263171
            ],
            [
                -120.5691318,
                35.136706
            ],
            [
                -120.5713634,
                35.1340387
            ],
            [
                -120.5916194,
                35.1462514
            ],
            [
                -120.6034641,
                35.1392328
            ],
            [
                -120.6353931,
                35.1344599
            ]
        ]
    ]
}
```

```
launchContext: {
            stealth: fasle,
            useChrome : false,
            launchOptions: {
                headless :true,
                args: [
                    // this is needed to access cross-domain iframes
                    '--disable-web-security',
                    '--no-sandbox',
                    //'--disable-setuid-sandbox',
                    '--disable-features=IsolateOrigins,site-per-process',
                    `--lang=${language}`, // force language at browser level
                ],
            }
        },

```

**Comment by beshoo** [comment]
Server: Linux CentOs 7.7

**Comment by beshoo** [comment]
The problem is from the stealth mode.
If any one have this problem turn stealth off

SOLVED

**Comment by metalwarrior665** [comment]
We will remove the stealth completely soon
