### ISSUE TITLE
The main function of the actor threw an exception running the latest in Ampify

### ISSUE THREAD

**Issue by gateway** [drobnikj/crawler-google-places#54]
2020-07-19T19:42:26.841Z Starting X virtual framebuffer using: Xvfb :99 -ac -screen 0 1280x720x16 -nolisten tcp
2020-07-19T19:42:26.842Z Executing main command
2020-07-19T19:42:26.842Z _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
2020-07-19T19:42:27.912Z INFO  System info {"apifyVersion":"0.21.0","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.18.0"}
2020-07-19T19:42:28.338Z ERROR The function passed to Apify.main() threw an exception:
2020-07-19T19:42:28.339Z   TypeError: Cannot destructure property 'geojson' of 'location' as it is undefined.
2020-07-19T19:42:28.339Z       at findPointsInPolygon (/home/myuser/src/polygon.js:94:13)
2020-07-19T19:42:28.339Z       at /home/myuser/src/main.js:64:24
2020-07-19T19:42:28.340Z       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-07-19T19:42:28.340Z       at async run (/home/myuser/node_modules/apify/build/actor.js:194:13)

**Comment by zzbazza** [comment]
@gateway can you please include input for your run?

**Comment by metalwarrior665** [comment]
@zzbazza I think even if we don't get the input, the scraper should not fail like this. Either the input is invalid and it should fail fast or it is an internal error and it should be displayed properly.

**Comment by metalwarrior665** [comment]
I haven't seen this error for a long time and we don't know how to reproduce it so closing.
