### ISSUE TITLE
Cannot read property 'apifyProxyGroups' of undefined

### ISSUE THREAD

**Issue by HazelCuate** [drobnikj/crawler-google-places#80]
Hi! I'm getting the following exception when launching the app locally:

```
Info: All default local stores were purged.
Warning: You are not logged in with your Apify Account. Some features like Apify Proxy will not work. Call "apify login" to fix that.
Run: npm start

> crawler-google-places@1.0.0 start
> node ./src/main.js

INFO  System info {"apifyVersion":"0.21.8","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.19.0"}
ERROR The function passed to Apify.main() threw an exception:
  TypeError: Cannot read property 'apifyProxyGroups' of undefined
      at /home/hazel/Descargas/crawler-google-places-master/src/main.js:55:21
      at async run (/home/hazel/Descargas/crawler-google-places-master/node_modules/apify/build/actor.js:194:13)
npm ERR! code 91
[2020-10-29T10_55_54_033Z-debug.log](https://github.com/drobnikj/crawler-google-places/files/5457841/2020-10-29T10_55_54_033Z-debug.log)

npm ERR! path /home/hazel/Descargas/crawler-google-places-master
npm ERR! command failed
npm ERR! command sh -c node ./src/main.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hazel/.npm/_logs/2020-10-29T10_55_54_033Z-debug.log
Error: npm exited with code 91
```
I just want to run the app in my system and I don't have an Apify user.

This is the config that I'm using:
```
{
  "searchString": "Lawyers",
  "language": "en",
  "maxCrawledPlaces": 200,
  "lat": "37.9144677",
  "lng": "-1.2708565",
  "zoom": 10,
  "maxAutomaticZoomOut": 0,
  "maxConcurrency": 2,
  "maxPageRetries": 3
}
```

**Comment by HazelCuate** [comment]
I'm using this config:
```
{
  "searchString": "Lawyers",
  "language": "en",
  "maxCrawledPlaces": 200,
  "lat": "37.9144677",
  "lng": "-1.2708565",
  "zoom": 10,
  "maxAutomaticZoomOut": 0,
  "maxConcurrency": 2,
  "maxPageRetries": 3
}
```

**Comment by metalwarrior665** [comment]
Thanks, I'm fixing it right now.

**Comment by HazelCuate** [comment]
> Thanks, I'm fixing it right now.

Thank you!

**Comment by metalwarrior665** [comment]
Fixed in the latest commit
