### ISSUE TITLE
Error: Apify Proxy password must be provided

### ISSUE THREAD

**Issue by HazelCuate** [drobnikj/crawler-google-places#81]
Hi! My [previous issue](https://github.com/drobnikj/crawler-google-places/issues/80) is fixed but now it's asking me to provide an Apify Proxy password but I don't want to use a proxy. ¿Am I always supposed to use the Apify Proxy?

```
Info: All default local stores were purged.
Warning: You are not logged in with your Apify Account. Some features like Apify Proxy will not work. Call "apify login" to fix that.
Run: npm start

> crawler-google-places@1.0.0 start
> node ./src/main.js

INFO  System info {"apifyVersion":"0.21.8","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.19.0"}
WARN  INPUT DEPRECATION: searchString field has been deprecated and will be removed soon! Please use searchStringsArray instead
INFO  Start urls are:
[ 'https://www.google.com/maps/@37.9144677,-1.2708565,10z/search' ]
ERROR The function passed to Apify.main() threw an exception:
  Error: Apify Proxy password must be provided using options.password or the "APIFY_PROXY_PASSWORD" environment variable.If you add the "APIFY_TOKEN" environment variable, the password will be automatically inferred.
      at ProxyConfiguration._setPasswordIfToken (/home/hazel/Descargas/crawler-google-places-master/node_modules/apify/build/proxy_configuration.js:295:19)
      at ProxyConfiguration.initialize (/home/hazel/Descargas/crawler-google-places-master/node_modules/apify/build/proxy_configuration.js:192:24)
      at Object.exports.createProxyConfiguration (/home/hazel/Descargas/crawler-google-places-master/node_modules/apify/build/proxy_configuration.js:544:30)
      at /home/hazel/Descargas/crawler-google-places-master/src/main.js:142:44
      at async run (/home/hazel/Descargas/crawler-google-places-master/node_modules/apify/build/actor.js:194:13)
npm ERR! code 91
npm ERR! path /home/hazel/Descargas/crawler-google-places-master
npm ERR! command failed
npm ERR! command sh -c node ./src/main.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hazel/.npm/_logs/2020-10-29T12_12_52_255Z-debug.log
Error: npm exited with code 91
```

I'm trying to execute it **locally** with the following config:
```
{
  "searchString": "Lawyers",
  "language": "en",
  "maxCrawledPlaces": 200,
  "lat": "37.9144677",
  "lng": "-1.2708565",
  "zoom": 10,
  "maxAutomaticZoomOut": 0,
  "maxConcurrency": 2,
  "maxPageRetries": 3
}
```

**Comment by metalwarrior665** [comment]
Pass in also

```
"proxyConfig": { "useApifyProxy": false }
```
