### ISSUE TITLE
waiting for selector `[jsaction="pane.paginationSection.nextPage"]` failed: timeout 60000ms exceeded

### ISSUE THREAD

**Issue by HazelCuate** [drobnikj/crawler-google-places#84]
I'm having the following error in loop:
```
Info: All default local stores were purged.
Warning: You are not logged in with your Apify Account. Some features like Apify Proxy will not work. Call "apify login" to fix that.
Run: npm start

> crawler-google-places@1.0.0 start
> node ./src/main.js

INFO  System info {"apifyVersion":"0.21.8","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.19.0"}
WARN  INPUT DEPRECATION: searchString field has been deprecated and will be removed soon! Please use searchStringsArray instead
INFO  Start urls are:
[ 'https://www.google.com/maps/@37.9144677,-1.2708565,10z/search' ]
INFO  PuppeteerCrawler:AutoscaledPool:Snapshotter: Setting max memory of this run to 967 MB. Use the APIFY_MEMORY_MBYTES environment variable to override it.
INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}                                                                                                                        
INFO  Launching Puppeteer {"args":["--disable-web-security","--disable-features=IsolateOrigins,site-per-process","--lang=en","--no-sandbox","--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"],"timeout":15000,"headless":true,"useChrome":false,"defaultViewport":{"width":1366,"height":768}}                                                                                                                                                                 
INFO  [SEARCH]: Start enqueuing places details for search --- Lawyers https://www.google.com/maps/@37.9144677,-1.2708565,10z/search?hl=en
INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":1,"desiredConcurrency":1,"systemStatus":{"isSystemIdle":false,"memInfo":{"isOverloaded":true,"limitRatio":0.2,"actualRatio":1},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":0.102},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":0}}}                                                                                                                                
INFO  Statistics: PuppeteerCrawler request statistics: {"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":null,"requestsFinishedPerMinute":0,"requestsFailedPerMinute":0,"requestTotalDurationMillis":0,"requestsTotal":0,"crawlerRuntimeMillis":60125,"retryHistogram":[]}                                                                  
ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/@37.9144677,-1.2708565,10z/search?hl=en","retryCount":1,"id":"M1kj6CxAnHJozw7"}                                                                                                                                       
  [SEARCH]: waiting for selector `[jsaction="pane.paginationSection.nextPage"]` failed: timeout 60000ms exceeded (Stack trace was omitted for retires requests. Set up debug mode to see it.)
```
...using the following config:
```
{
  "searchString": "Lawyers",
  "language": "en",
  "proxyConfig": { "useApifyProxy": false },
  "maxCrawledPlaces": 200,
  "lat": "37.9144677",
  "lng": "-1.2708565",
  "zoom": 10,
  "maxAutomaticZoomOut": 0,
  "maxConcurrency": 2,
  "maxPageRetries": 3
}
```
I guess this is because the URL might be malformed, it's missing the _searchString/searchStringsArray_ fields so Google Maps shows no results.

**Comment by metalwarrior665** [comment]
The URL itself is not malformed as it types in the search string. I saw this error happen from time to time and it might be blocking or just slow load. Did you see what happened in headful mode?

We plan to introduce a new system for error handling that should make catching/explaining these simple.

**Comment by HazelCuate** [comment]
It fails with the following error when I set useChrome to true:
```
INFO  System info {"apifyVersion":"0.21.8","apifyClientVersion":"0.6.0","osType":"Linux","nodeVersion":"v12.19.0"}
INFO  Start urls are:
[ 'https://www.google.com/maps/@37.9144677,-1.2708565,10z/search' ]
INFO  PuppeteerCrawler:AutoscaledPool:Snapshotter: Setting max memory of this run to 967 MB. Use the APIFY_MEMORY_MBYTES environment variable to override it.
INFO  PuppeteerCrawler:AutoscaledPool: state {"currentConcurrency":0,"desiredConcurrency":2,"systemStatus":{"isSystemIdle":true,"memInfo":{"isOverloaded":false,"limitRatio":0.2,"actualRatio":null},"eventLoopInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"cpuInfo":{"isOverloaded":false,"limitRatio":0.4,"actualRatio":null},"clientInfo":{"isOverloaded":false,"limitRatio":0.3,"actualRatio":null}}}                                                                                                                        
INFO  Launching Puppeteer {"args":["--disable-web-security","--disable-features=IsolateOrigins,site-per-process","--lang=en","--no-sandbox"],"timeout":15000,"headless":false,"useChrome":true,"executablePath":"google-chrome","defaultViewport":{"width":1366,"height":768}}                                                                                      
ERROR PuppeteerCrawler:PuppeteerPool: Browser launch failed {"id":0}
  Error: Failed to launch the browser process! spawn google-chrome ENOENT
  
  TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
  
      at onClose (/home/hazel/Descargas/crawler-google-places-master/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
      at ChildProcess.<anonymous> (/home/hazel/Descargas/crawler-google-places-master/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:185:85)
      at ChildProcess.emit (events.js:314:20)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
      at onErrorNT (internal/child_process.js:469:16)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)
ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"https://www.google.com/maps/@37.9144677,-1.2708565,10z/search","retryCount":1,"id":"M1kj6CxAnHJozw7"}                                                                                                                                             
  Error: Failed to launch the browser process! spawn google-chrome ENOENT
```

Why not to use the following URL so it doesn't have to type though? https://www.google.com/maps/search/Lawyers/@37.9144677,-1.2708565,10z

By the way, the final stacktrace in headless mode is:
```
ERROR Page https://www.google.com/maps/@37.9144677,-1.2708565,10z/search?hl=en failed 4 times! It will not be retired. Check debug fields in dataset to find the issue.
  TimeoutError: waiting for selector `[jsaction="pane.paginationSection.nextPage"]` failed: timeout 60000ms exceeded
      at new WaitTask (/home/hazel/Descargas/crawler-google-places-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:411:34)
      at DOMWorld.waitForSelector (/home/hazel/Descargas/crawler-google-places-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:319:26)
      at Frame.waitForSelector (/home/hazel/Descargas/crawler-google-places-master/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
      at Page.waitForSelector (/home/hazel/Descargas/crawler-google-places-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1322:33)
      at enqueueAllPlaceDetails (/home/hazel/Descargas/crawler-google-places-master/src/enqueue_places_crawler.js:135:20)
```

**Comment by metalwarrior665** [comment]
I added better handling of the consent screen. But it is still a bit clunky because it depends on how fast it shows. Can you try it now pls?

**Comment by HazelCuate** [comment]
Sure. Now I get many `ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue`: https://pastebin.com/teK2dTMV

Both in headless and headful modes.

Btw, where are stored the results once it finishes?

Thank you.

**Comment by metalwarrior665** [comment]
Interesting. That is something from the Globalize package. I did a small update, can you pull and try again? I need to discuss details with other dev who added this.

Results are in apify_storage/datasets/default

**Comment by HazelCuate** [comment]
Ok, now it's working perfectly [fine](https://media.tenor.com/images/41c62170d703344338b8b7dfe63e4aaa/tenor.gif). Thank you!

`
INFO  [STATS]: failed: 0 | ok: 151 | outOfPolygon: 0 | outOfPolygonCached: 0 | places: 150 | maps: 1
`

**Comment by metalwarrior665** [comment]
Thanks for testing this!
